services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "YourStrong@Passw0rd"
      ACCEPT_EULA: "Y"
    healthcheck:
      test: ["CMD", "/bin/bash", "-c", "timeout 5 bash -c '</dev/tcp/localhost/1433' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 50
      start_period: 60s

  lambda:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "9000:8080"
    environment:
      DB_HOST: "db"
      DB_USER: "sa"
      DB_PASSWORD: "YourStrong@Passw0rd"
      DB_NAME: "master"
    volumes:
      - ./lambda_function.py:/var/task/lambda_function.py
    command: lambda_function.handler
    depends_on:
      db:
        condition: service_healthy

  test:
    image: curlimages/curl:latest
    depends_on:
      - lambda
    command: >
      sh -c "sleep 5 && curl -X POST 'http://lambda:8080/2015-03-31/functions/function/invocations' -d '{}'"