  services:
    lambda:
      build:
        context: .
        dockerfile: ./Dockerfile
      ports:
        - "9000:8080"
      environment:
        DEVELOPER: "hector"
        NODE_ENV: "development"
        PLAYWRIGHT_BROWSERS_PATH: "/var/task/node_modules/@sparticuz/chromium/bin"
      volumes:
        - ./lambda_function.js:/var/task/lambda_function.js
      command: lambda_function.handler

    test:
      image: curlimages/curl:latest
      depends_on:
        - lambda
      command: >
        sh -c "sleep 5 && curl -X POST 'http://lambda:8080/2015-03-31/functions/function/invocations' -d '{}'"